# ── admin/config.yml ──

backend:
  name: git-gateway
  repo: GDSGlasgow/GDSGlasgow.github.io
  branch: dev-pg
  identity_url: https://auth.decapbridge.com/sites/68a9faf2-f948-4c16-8c0c-f60c660937c1
  gateway_url: https://gateway.decapbridge.com

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://gdsglasgow.github.io

collections:

  # ---------------------- POSTS ----------------------
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # Uploads saved alongside each post .md file
    media_folder: "assets/img"
    public_folder: "/assets/img"
    fields:
      - { label: "Layout",        name: "layout",        widget: "hidden",  default: "post" }
      - { label: "Title",         name: "title",         widget: "string" }
      - { label: "Date",          name: "date",          widget: "datetime" }
      - { label: "Author",        name: "author",        widget: "string" }
      - { label: "Description",   name: "description",   widget: "text",     required: false }
      - { label: "Tags",          name: "tags",          widget: "list" }
      - { label: "Categories",    name: "categories",    widget: "list" }
      - { label: "Thumbnail",     name: "thumbnail",     widget: "image",    required: false }
      - { label: "Body",          name: "body",          widget: "markdown" }

  # --------------------- PROJECTS ---------------------
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    # Shared project images folder
    media_folder: "assets/img/project_images"
    public_folder: "/assets/img/project_images"
    fields:
      - { label: "Layout",               name: "layout",              widget: "hidden", default: "page" }
      - { label: "Title",                name: "title",               widget: "string" }
      - { label: "Description",          name: "description",         widget: "text",    required: false }
      - { label: "Image",                name: "img",                 widget: "image" }
      - { label: "Importance (1-5)",     name: "importance",          widget: "number",  min: 1, max: 5 }
      - { label: "Category",             name: "category",            widget: "string" }
      - { label: "Related Publications", name: "related_publications", widget: "string", required: false }
      - { label: "Body",                 name: "body",                widget: "markdown" }

  # ---------------------- TEAM -----------------------
  - name: "team"
    label: "Team Members"
    folder: "_team"
    create: true
    slug: "{{slug}}"
    # Shared team profile images folder
    media_folder: "assets/img/team_profiles"
    public_folder: "/assets/img/team_profiles"
    fields:
      - { label: "Layout",     name: "layout",     widget: "hidden", default: "team" }
      - { label: "Inline?",    name: "inline",     widget: "boolean" }
      - { label: "Group",      name: "group",      widget: "string" }
      - { label: "Group Rank", name: "group_rank", widget: "number" }
      - { label: "Weight",     name: "weight",     widget: "number" }
      - { label: "Title",      name: "title",      widget: "string" }
      - { label: "Last Name",  name: "lastname",   widget: "string" }
      - { label: "Description",name: "description", widget: "text" }
      - { label: "Publications",name: "publications", widget: "string", required: false }
      - { label: "Teaser",     name: "teaser",     widget: "markdown" }
      - label: "Profile"
        name: "profile"
        widget: "object"
        fields:
          - { label: "Name",     name: "name",     widget: "string" }
          - { label: "Position", name: "position", widget: "string" }
          - { label: "Align",    name: "align",    widget: "select", options: ["left","right"] }
          - { label: "Image",    name: "image",    widget: "image" }
          - { label: "Email",    name: "email",    widget: "string" }
          - { label: "Twitter",  name: "twitter",  widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
          - { label: "ORCID",    name: "orcid",    widget: "string", required: false }
          - { label: "Address",  name: "address",  widget: "text",    required: false }
          - { label: "UoG URL",  name: "uofg",     widget: "string", required: false }

  # ---------------------- NEWS -----------------------
  - name: "news"
    label: "News"
    folder: "_news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # If news uploads are rare, save alongside entry
    media_folder: "assets/img"
    public_folder: "/assets/img"
    fields:
      - { label: "Layout",         name: "layout",        widget: "hidden", default: "post" }
      - { label: "Date",           name: "date",          widget: "datetime" }
      - { label: "Inline?",        name: "inline",        widget: "boolean" }
      - { label: "Related Posts?", name: "related_posts", widget: "boolean" }
      - { label: "Body",           name: "body",          widget: "markdown" }

  # --------------------- PARTNERS ---------------------
  - name: "partners"
    label: "Partners"
    folder: "_partners"
    create: true
    slug: "{{slug}}"
    # Shared partner logos folder
    media_folder: "assets/img/partners"
    public_folder: "/assets/img/partners"
    fields:
      - { label: "Layout",      name: "layout",     widget: "hidden", default: "page" }
      - { label: "Title",       name: "title",      widget: "string" }
      - { label: "Description", name: "description", widget: "text",   required: false }
      - { label: "Logo/Image",  name: "img",         widget: "image" }
      - { label: "Redirect URL",name: "redirect",    widget: "string", required: false }
      - { label: "Importance",   name: "importance",  widget: "number", min: 1, max: 5 }
      - { label: "Category",     name: "category",    widget: "string", required: false }
